repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
# -   repo: https://github.com/asottile/reorder-python-imports
#     rev: v3.13.0
#     hooks:
#     -   id: reorder-python-imports
#         exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
#         args: [--py39-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args:
          - --in-place  # Modify files directly
          - --aggressive  # Optional: apply fixes more aggressively
          - --max-line-length=120  # Optional: enforce line length
-   repo: https://github.com/psf/black
    rev: 24.8.0  # Check for the latest version
    hooks:
    -   id: black
        args: ['--line-length=120', '--skip-string-normalization']
# -   repo: https://github.com/PyCQA/flake8
#     rev: 7.1.1
#     hooks:
#     -   id: flake8
#         args: [
#           --max-line-length=150,
#           --exclude=migrations,scripts,tenv,lib
#         ]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.11.2
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-pyyaml]
#         exclude: ^testing/resources/
